# Generated by Django 3.1.2 on 2020-10-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=25)),
                ('placa', models.CharField(max_length=10)),
                ('kilometragem_inicial', models.PositiveIntegerField()),
                ('kilometragem_revisao', models.PositiveSmallIntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rt.empresa')),
            ],
            options={
                'db_table': 'veiculos',
            },
        ),
    ]
