# Generated by Django 3.1.2 on 2020-11-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grau_emergencia', models.PositiveSmallIntegerField(choices=[(1, 'LEVE'), (2, 'MODERADO'), (3, 'URGENTE')])),
                ('descricao', models.CharField(max_length=250)),
                ('ok', models.BooleanField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DISPONÍVEL'), (2, 'AUSENTE'), (3, 'INOPERANTE')], default=1),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'DISPONÍVEL'), (2, 'AUSENTE'), (3, 'INOPERANTE')], default=1),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
