# Generated by Django 3.1.2 on 2020-10-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt', '0002_auto_20201025_1417'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='duncionarios',
        ),
    ]
