# Generated by Django 3.1.2 on 2020-10-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt', '0003_auto_20201025_1419'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
